DROP TABLE IF EXISTS time_logs;
DROP TABLE IF EXISTS project_assignments;
DROP TABLE IF EXISTS invoice_projects;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS staff_skills;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS rate_cards;

DROP SCHEMA IF EXISTS allocationSystemV2;